[package]
name = "shuttle-aws-rds"
version = "0.46.0"
edition = "2021"
license = "Apache-2.0"
description = "Plugin to provision AWS RDS resources"
repository = "https://github.com/shuttle-hq/shuttle"
keywords = ["shuttle-service", "rds"]

[dependencies]
async-trait = "0.1.56"
paste = "1.0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shuttle-service = { path = "../../service", version = "0.46.0" }
sqlx = { version = "0.7.1", optional = true }

[features]
default = []

# Database
postgres = ["sqlx?/postgres"]
mysql = ["sqlx?/mysql"]
mariadb = ["sqlx?/mysql"]

# Add an sqlx Pool as a resource output type
sqlx = ["dep:sqlx", "sqlx/runtime-tokio", "sqlx/tls-rustls"]
sqlx-native-tls = ["dep:sqlx", "sqlx/runtime-tokio", "sqlx/tls-native-tls"]
