[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
anyhow = "1.0.62"
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
shuttle-secrets = "0.6.0"
shuttle-service = { version = "0.6.0", features = ["bot-serenity"] }
tracing = "0.1.35"
