[workspace]
members = [
  "cargo-shuttle",
  "codegen",
  "common",
  "deployer",
  "gateway",
  "next",
  "proto",
  "provisioner",
  "service"
]
exclude = [
  "e2e",
  "examples",
  "plugins",
  "resources/aws-rds",
  "resources/persist",
  "resources/secrets",
  "resources/shared-db"
]
