[workspace]
members = [
  "admin",
  "auth",
  "cargo-shuttle",
  "codegen",
  "common",
  "deployer",
  "gateway",
  "proto",
  "provisioner",
  "runtime",
  "service",
]

exclude = [
  "e2e",
  "examples",
  "resources/aws-rds",
  "resources/persist",
  "resources/secrets",
  "resources/shared-db",
  "resources/static-folder",
  "services",
]

[workspace.package]
version = "0.14.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/shuttle-hq/shuttle"

# https://doc.rust-lang.org/cargo/reference/workspaces.html#the-workspacedependencies-table
[workspace.dependencies]
shuttle-codegen = { path = "codegen", version = "0.14.0" }
shuttle-common = { path = "common", version = "0.14.0" }
shuttle-proto = { path = "proto", version = "0.14.0" }
shuttle-service = { path = "service", version = "0.14.0" }

anyhow = "1.0.66"
async-trait = "0.1.58"
axum = { version = "0.6.0", default-features = false }
base64 = "0.13.1"
bollard = "0.14.0"
bytes = "1.3.0"
cap-std = "1.0.2"
cargo = "0.69.0"
cargo_metadata = "0.15.3"
chrono = { version = "0.4.23", default-features = false }
clap = { version = "4.0.27", features = ["derive"] }
crossbeam-channel = "0.5.7"
crossterm = "0.25.0"
ctor = "0.1.26"
dirs = "5.0.0"
flate2 = "1.0.25"
fqdn = "0.2.3"
futures = "0.3.27"
headers = "0.3.8"
home = "0.5.4"
http = "0.2.8"
hyper = "0.14.23"
jsonwebtoken = { version = "8.2.0" }
once_cell = "1.16.0"
opentelemetry = { version = "0.18.0", features = ["rt-tokio"] }
opentelemetry-http = "0.7.0"
pin-project = "1.0.12"
pipe = "0.4.0"
portpicker = "0.1.1"
prost = "0.11.8"
prost-types = "0.11.0"
rand = "0.8.5"
reqwest = "0.11.13"
ring = "0.16.20"
rmp-serde = "1.1.1"
serde = { version = "1.0.148", default-features = false }
serde_json = "1.0.89"
sqlx = "0.6.2"
strum = { version = "0.24.1", features = ["derive"] }
tempfile = "3.4.0"
thiserror = "1.0.37"
tar = "0.4.38"
tokio = { version = "1.22.0" }
toml = "0.5.9"
toml_edit = "0.15.0"
tonic = "0.8.3"
tonic-build = "0.8.3"
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["trace"] }
tracing = { version = "0.1.37", default-features = false }
tracing-opentelemetry = "0.18.0"
tracing-subscriber = { version = "0.3.16", default-features = false, features = [
  "registry",
  "std",
] }
ttl_cache = "0.5.1"
utoipa = { version = "3.2.1", features = [ "uuid", "chrono" ] }
utoipa-swagger-ui = { version = "3.1.3", features = ["axum"] }
uuid = "1.2.2"
