[workspace]
resolver = "2"
members = [
  "admin",
  "auth",
  "builder",
  "cargo-shuttle",
  "codegen",
  "common",
  "common-tests",
  "deployer",
  "gateway",
  "logger",
  "orchestrator",
  "proto",
  "provisioner",
  "resource-recorder",
  "runtime",
  "service",
]
exclude = [
  "e2e",
  "examples",
  "resources",
  "services",
]

[workspace.package]
version = "0.29.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/shuttle-hq/shuttle"

# https://doc.rust-lang.org/cargo/reference/workspaces.html#the-workspacedependencies-table
[workspace.dependencies]
shuttle-codegen = { path = "codegen", version = "0.29.0" }
shuttle-common = { path = "common", version = "0.29.0" }
shuttle-common-tests = { path = "common-tests", version = "0.29.0" }
shuttle-orchestrator = { path = "orchestrator", version = "0.29.0" }
shuttle-proto = { path = "proto", version = "0.29.0" }
shuttle-service = { path = "service", version = "0.29.0" }

anyhow = "1.0.66"
async-trait = "0.1.58"
axum = { version = "0.6.0", default-features = false }
axum-sessions = "0.4.1"
base64 = "0.13.1"
bollard = "0.15.0"
bytes = "1.3.0"
cap-std = "1.0.2"
cargo_metadata = "0.15.3"
chrono = { version = "0.4.23", default-features = false }
colored = "2.0.0"
clap = { version = "4.2.7", features = ["derive"] }
crossbeam-channel = "0.5.7"
crossterm = "0.27.0"
ctor = "0.1.26"
dirs = "5.0.0"
dunce = "1.0.4"
flate2 = "1.0.25"
fqdn = "0.2.3"
futures = "0.3.27"
headers = "0.3.8"
home = "0.5.4"
http = "0.2.8"
hyper = "0.14.23"
# not great, but waiting for WebSocket changes to be merged
hyper-reverse-proxy = { git = "https://github.com/chesedo/hyper-reverse-proxy", branch = "bug/host_header" }
jsonwebtoken = "8.2.0"
once_cell = "1.16.0"
opentelemetry = { version = "0.19.0", features = ["rt-tokio"] }
opentelemetry-http = "0.8.0"
opentelemetry-otlp = "0.12.0"
opentelemetry-proto = "0.2.0"
percent-encoding = "2.2"
pin-project = "1.0.12"
pipe = "0.4.0"
portpicker = "0.1.1"
pretty_assertions = "1.3.0"
prost = "0.11.8"
prost-types = "0.11.0"
rand = "0.8.5"
reqwest = { version = "0.11.13", default-features = false, features = ["rustls-tls"] }
ring = "0.16.20"
rmp-serde = "1.1.1"
semver = { version = "1.0.17", features = ["serde"] }
serde = { version = "1.0.148", default-features = false }
serde_json = "1.0.89"
sqlx = "0.7.1"
strfmt = "0.2.2"
strum = { version = "0.24.1", features = ["derive"] }
tempfile = "3.4.0"
thiserror = "1.0.37"
tar = "0.4.38"
tokio = "1.22.0"
tokio-stream = "0.1.11"
toml = "0.7.6"
toml_edit = "0.19.14"
tonic = "0.8.3"
tonic-build = "0.8.3"
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["trace"] }
tracing = { version = "0.1.37", default-features = false }
tracing-opentelemetry = "0.19.0"
tracing-subscriber = { version = "0.3.16", default-features = false, features = [
  "registry",
] }
ttl_cache = "0.5.1"
os_pipe = { version = "1.1.4" }
utoipa = { version = "3.2.1", features = [ "uuid", "chrono" ] }
utoipa-swagger-ui = { version = "3.1.3", features = ["axum"] }
ulid = "1.0.0"
uuid = "1.2.2"
