[workspace]
members = [
  "admin",
  "auth",
  "cargo-shuttle",
  "codegen",
  "common",
  "deployer",
  "gateway",
  "proto",
  "provisioner",
  "service"
]

exclude = [
  "e2e",
  "examples",
  "resources/aws-rds",
  "resources/persist",
  "resources/secrets",
  "resources/shared-db",
  "resources/static-folder"
]

[workspace.package]
version = "0.10.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/shuttle-hq/shuttle"

# https://doc.rust-lang.org/cargo/reference/workspaces.html#the-workspacedependencies-table
[workspace.dependencies]
shuttle-codegen = { path = "codegen", version = "0.10.0" }
shuttle-common = { path = "common", version = "0.10.0" }
shuttle-proto = { path = "proto", version = "0.10.0" }
shuttle-service = { path = "service", version = "0.10.0" }

anyhow = "1.0.66"
async-trait = "0.1.58"
axum = "0.6.0"
chrono = "0.4.23"
clap = { version = "4.0.27", features = [ "derive" ] }
headers = "0.3.8"
hyper = "0.14.23"
once_cell = "1.16.0"
opentelemetry = { version = "0.18.0", features = ["rt-tokio"] }
opentelemetry-datadog = { version = "0.6.0", features = ["reqwest-client"] }
opentelemetry-http = "0.7.0"
rand = "0.8.5"
serde = "1.0.148"
serde_json = "1.0.89"
portpicker = "0.1.1"
thiserror = "1.0.37"
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["trace"] }
tracing = "0.1.37"
tracing-opentelemetry = "0.18.0"
tracing-subscriber = "0.3.16"
uuid = "1.2.2"
