version: "3"

services:
  deployer:
    entrypoint:
      - /bin/bash
      - -c
      - |
        mkdir -p $$CARGO_HOME
        cat<<EOF > $$CARGO_HOME/config.toml
        [patch.crates-io]
        shuttle-service = { path = "/usr/src/shuttle/service" }
        EOF

        until </dev/tcp/provisioner/8000
        do
          >&2 echo "provisioner is not available yet - sleeping"
          sleep 1
        done

        exec /usr/local/bin/service "$${@:0}"
    volumes:
      - .:/usr/src/shuttle

    build:
      context: .
      dockerfile: Containerfile
      args:
        crate: shuttle-deployer
    image: "${CONTAINER_REGISTRY}/deployer:dev"

  provisioner:
    entrypoint:
      - /bin/bash
      - -c
      - |
        until </dev/tcp/db/5432
        do
          >&2 echo "DB is not available yet - sleeping"
          sleep 1
        done

        >&2 echo "DB is available - starting provisioner"

        exec /usr/local/bin/service "$${@:0}"
    build:
      context: .
      dockerfile: Containerfile
      args:
        crate: shuttle-provisioner
    image: "${CONTAINER_REGISTRY}/provisioner:dev"
