version: "3"

services:
  api:
    entrypoint:
      - /bin/bash
      - -c
      - |
        mkdir -p /var/lib/shuttle/crates

        cat<<EOF > /var/lib/shuttle/users.toml
        [test-key]
        name = "tester"
        projects = []
        EOF

        mkdir -p $$CARGO_HOME
        cat<<EOF > $$CARGO_HOME/config.toml
        [patch.crates-io]
        shuttle-service = { path = "/usr/src/shuttle/service" }
        EOF

        until </dev/tcp/provisioner/8000
        do
          >&2 echo "provisioner is not available yet - sleeping"
          sleep 1
        done

        exec /usr/local/bin/service "$${@:0}"
    volumes:
      - .:/usr/src/shuttle

    build:
      context: .
      dockerfile: Containerfile
      args:
        crate: shuttle-api
    image: "${CONTAINER_REGISTRY}/api:dev"

  # TODO: add health check for mongodb here
  provisioner:
    entrypoint:
      - /bin/bash
      - -c
      - |
        until </dev/tcp/pg/5432
        do
          >&2 echo "PG is not available yet - sleeping"
          sleep 1
        done

        until </dev/tcp/mongodb/27017
        do
          >&2 echo "mongoDB is not available yet - sleeping"
          sleep 1
        done

        >&2 echo "DBs are available - starting provisioner"

        exec /usr/local/bin/service "$${@:0}"
    build:
      context: .
      dockerfile: Containerfile
      args:
        crate: shuttle-provisioner
    image: "${CONTAINER_REGISTRY}/provisioner:dev"
