version: "3"

services:
  provisioner:
    entrypoint:
      - /bin/bash
      - -c
      - |
        until </dev/tcp/postgres/5432
        do
          >&2 echo "PG is not available yet - sleeping"
          sleep 1
        done

        until </dev/tcp/mongodb/27017
        do
          >&2 echo "mongoDB is not available yet - sleeping"
          sleep 1
        done

        >&2 echo "DBs are available - starting provisioner"

        exec /usr/local/bin/service "$${@:0}"
    ports:
    - published: 5000
      target: 8000
