[package]
name = "shuttle-salvo"
version = "0.56.0"
edition = "2021"
license = "Apache-2.0"
description = "Service implementation to run a salvo webserver on shuttle"
repository = "https://github.com/shuttle-hq/shuttle"
keywords = ["shuttle-service", "salvo"]

[workspace]

[dependencies]
salvo = "0.83"
shuttle-runtime = { path = "../../runtime", version = "0.56.0", default-features = false }
