[package]
name = "shuttle-gateway"
version = "0.7.2"
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1.52"
axum = { version = "0.5.8", features = [ "headers" ] }
base64 = "0.13"
bollard = "0.13"
chrono = "0.4"
clap = { version = "4.0.0", features = [ "derive" ] }
fqdn = "0.2.2"
futures = "0.3.21"
http = "0.2.8"
hyper = { version = "0.14.19", features = [ "stream" ] }
# not great, but waiting for WebSocket changes to be merged
hyper-reverse-proxy = { git = "https://github.com/chesedo/hyper-reverse-proxy", branch = "bug/host_header" }
once_cell = "1.14.0"
opentelemetry = { version = "0.18.0", features = ["rt-tokio"] }
opentelemetry-datadog = { version = "0.6.0", features = ["reqwest-client"] }
opentelemetry-http = "0.7.0"
rand = "0.8.5"
serde = { version = "1.0.137", features = [ "derive" ] }
serde_json = "1.0.81"
sqlx = { version = "0.5.11", features = [ "sqlite", "json", "runtime-tokio-rustls", "migrate" ] }
tokio = { version = "1.17", features = [ "full" ] }
tower = { version = "0.4.13", features = [ "steer" ] }
tower-http = { version = "0.3.4", features = ["trace"] }
tracing = "0.1.35"
tracing-opentelemetry = "0.18.0"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
uuid = { version = "1.2.1", features = [ "v4" ] }

[dependencies.shuttle-common]
version = "0.7.2"
path = "../common"

[dev-dependencies]
anyhow = "1"
base64 = "0.13"
colored = "2"
portpicker = "0.1"
snailquote = "0.3"
tempfile = "3.3.0"
