[package]
name = "shuttle-gateway"
version = "0.7.3"
edition = "2021"
publish = false

[dependencies]
acme2 = "0.5.1"
async-trait = "0.1.58"
axum = { version = "0.6.0", features = [ "headers" ] }
axum-server = { version = "0.4.4", features = [ "tls-rustls" ] }
base64 = "0.13.1"
bollard = "0.13.0"
chrono = "0.4.22"
clap = { version = "4.0.27", features = [ "derive" ] }
fqdn = "0.2.3"
futures = "0.3.25"
http = "0.2.8"
hyper = { version = "0.14.23", features = [ "stream" ] }
# not great, but waiting for WebSocket changes to be merged
hyper-reverse-proxy = { git = "https://github.com/chesedo/hyper-reverse-proxy", branch = "bug/host_header" }
instant-acme = "0.1.1"
lazy_static = "1.4.0"
once_cell = "1.16.0"
opentelemetry = { version = "0.18.0", features = ["rt-tokio"] }
opentelemetry-datadog = { version = "0.6.0", features = ["reqwest-client"] }
opentelemetry-http = "0.7.0"
pem = "1.1.0"
rand = "0.8.5"
rcgen = "0.10.0"
rustls = "0.20.7"
rustls-pemfile = "1.0.1"
serde = { version = "1.0.148", features = [ "derive" ] }
serde_json = "1.0.89"
sqlx = { version = "0.6.2", features = [ "sqlite", "json", "runtime-tokio-native-tls", "migrate" ] }
strum = { version = "0.24.1", features = ["derive"] }
tokio = { version = "1.22.0", features = [ "full" ] }
tower = { version = "0.4.13", features = [ "steer" ] }
tower-http = { version = "0.3.4", features = ["trace"] }
tracing = "0.1.37"
tracing-opentelemetry = "0.18.0"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
uuid = { version = "1.2.2", features = [ "v4" ] }

[dependencies.shuttle-common]
version = "0.7.2"
path = "../common"
features = ["backend"]

[dev-dependencies]
anyhow = "1.0.66"
base64 = "0.13.1"
colored = "2.0.0"
portpicker = "0.1.1"
snailquote = "0.3.1"
tempfile = "3.3.0"

