[package]
name = "shuttle-gateway"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
acme2 = "0.5.1"
async-trait = { workspace = true }
axum = { workspace = true, features = [ "headers" ] }
axum-server = { version = "0.4.4", features = [ "tls-rustls" ] }
base64 = "0.13.1"
bollard = "0.13.0"
chrono = { workspace = true }
clap = { workspace = true }
fqdn = "0.2.3"
futures = "0.3.25"
http = "0.2.8"
hyper = { workspace = true, features = [ "stream" ] }
# not great, but waiting for WebSocket changes to be merged
hyper-reverse-proxy = { git = "https://github.com/chesedo/hyper-reverse-proxy", branch = "bug/host_header" }
instant-acme = "0.1.1"
lazy_static = "1.4.0"
num_cpus = "1.14.0"
once_cell = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-datadog = { workspace = true }
opentelemetry-http = { workspace = true }
pem = "1.1.0"
rand = { workspace = true }
rcgen = "0.10.0"
rustls = "0.20.7"
rustls-pemfile = "1.0.1"
serde = { workspace = true, features = [ "derive" ] }
serde_json = { workspace = true }
sqlx = { version = "0.6.2", features = [ "sqlite", "json", "runtime-tokio-native-tls", "migrate" ] }
strum = { version = "0.24.1", features = ["derive"] }
tokio = { version = "1.22.0", features = [ "full" ] }
tower = { workspace = true, features = [ "steer" ] }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
ttl_cache = "0.5.1"
uuid = { workspace = true, features = [ "v4" ] }

[dependencies.shuttle-common]
workspace = true
features = ["backend", "models"]

[dev-dependencies]
anyhow = { workspace = true }
base64 = "0.13.1"
colored = "2.0.0"
portpicker = { workspace = true }
snailquote = "0.3.1"
tempfile = "3.3.0"

