[package]
name = "shuttle-gateway"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"

clap = { version = "3.1", features = [ "derive", "env" ] }

tokio = { version = "1.17", features = [ "full" ] }
async-trait = "0.1.52"
futures = "0.3.21"

regex = "1.5.5"

hyper = { version = "0.14.17", features = [ "stream" ] }
axum = { version = "0.4.8", features = [ "headers" ] }
hyper-reverse-proxy = "0.5.1"
tower = { version = "0.4.12", features = [ "steer" ] }

bollard = "0.11.1"

sqlx = { version = "0.5.11", features = [ "sqlite", "json", "runtime-tokio-rustls" ] }

base64 = "0.13"
rand = "0.8.5"

convert_case = "0.5.0"

env_logger = "0.9.0"
log = "0.4.14"

shuttle-common = { version = "0.3", path = "../common" }
