[package]
name = "shuttle-gateway"
version = "0.1.0"
edition = "2021"
publish = false

[features]
testing = [ "anyhow", "tempfile" ]

[dependencies]
serde = { version = "1.0.137", features = [ "derive" ] }
serde_json = "1.0.81"

clap = { version = "3.1", features = [ "derive" ] }

tokio = { version = "1.17", features = [ "full" ] }
async-trait = "0.1.52"
futures = "0.3.21"

lazy_static = "1.4.0"
regex = "1.5.5"

http = "0.2.8"
hyper = { version = "0.14.19", features = [ "stream" ] }
hyper-reverse-proxy = "0.5.1"
axum = { version = "0.5.8", features = [ "headers" ] }
tower = { version = "0.4.13", features = [ "steer" ] }

bollard = "0.12"

chrono = "0.4"

sqlx = { version = "0.5.11", features = [ "sqlite", "json", "runtime-tokio-rustls", "migrate" ] }

base64 = "0.13"
rand = "0.8.5"

convert_case = "0.5.0"

env_logger = "0.9.0"
log = "0.4.14"

shuttle-common = { version = "0.3", path = "../common" }

anyhow = { version = "1", optional = true }
tempfile = { version = "3.3.0", optional = true }

[dev-dependencies]
anyhow = "1"
tempfile = "3.3.0"
snailquote = "0.3"
colored = "2"
portpicker = "0.1"
base64 = "0.13"
