[package]
name = "shuttle-axum-expanded"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
# most axum features can be enabled, but "tokio" and "ws" depend on socket2
# via "hyper/tcp" which is not compatible with wasi
axum = { version = "0.6.0", default-features = false }
futures-executor = "0.3.21"
http = "0.2.7"
tower-service = "0.3.1"
rmp-serde = { version = "1.1.1" }

[dependencies.shuttle-common]
path = "../../common"
default-features = false
features = ["axum-wasm"]
version = "0.8.0"
