[package]
name = "shuttle-auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
clap = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-datadog = { workspace = true }
serde = { workspace = true, features = [ "derive" ] }
sqlx = { version = "0.6.2", features = [ "sqlite", "json", "runtime-tokio-native-tls", "migrate" ] }
thiserror = { workspace = true }
tokio = { version = "1.22.0", features = [ "full" ] }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[dependencies.shuttle-common]
workspace = true
features = ["backend"]
