[package]
name = "cargo-shuttle"
version = "0.4.0"
edition = "2021"
license = "Apache-2.0"
description = "A cargo command for the shuttle platform (https://www.shuttle.rs/)"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.56"
bollard = "0.12.0"
cargo = "0.62.0"
cargo-edit = { version = "0.9.1", features = ["cli"] }
cargo_metadata = "0.14.2"
chrono = "0.4.19"
clap = { version = "3.1.18", features = ["derive", "env"] }
colored = "2.0.0"
crossterm = "0.23.2"
dirs = "4.0.0"
futures = "0.3.21"
indoc = "1.0.6"
portpicker = "0.1.1"
reqwest = { version = "0.11.10", features = ["json"] }
reqwest-middleware = "0.1.6"
reqwest-retry = "0.1.5"
semver = "1.0.9"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
tokio = "1.19.2"
toml = "0.5.9"
toml_edit = "0.14.4"
tracing = { version = "0.1.35", features = ["log"] }
url = "2.2.2"
uuid = { version = "1.1.1", features = ["v4"] }
webbrowser = "0.7.1"

[dependencies.shuttle-common]
version = "0.4.0"
path = "../common"

[dependencies.shuttle-service]
version = "0.4.0"
path = "../service"
features = ["loader"]

[dev-dependencies]
tempfile = "3.3.0"
test-context = "0.1.3"
# Tmp until this branch is merged and released
tokiotest-httpserver = { git = "https://github.com/shuttle-hq/tokiotest-httpserver", branch = "feat/body" }
tracing-subscriber = "0.3.14"
