[package]
name = "cargo-shuttle"
version = "0.48.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "CLI for the Shuttle platform (https://www.shuttle.rs/)"
homepage = "https://www.shuttle.rs"
default-run = "cargo-shuttle"

[dependencies]
shuttle-api-client = { workspace = true, default-features = true }
shuttle-common = { workspace = true, features = ["models"] }
shuttle-proto = { workspace = true, features = ["provisioner", "runtime-client"] }
shuttle-service = { workspace = true, features = ["builder", "runner"] }

anyhow = { workspace = true }
async-trait = { workspace = true }
bollard = { workspace = true }
cargo_metadata = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = ["env"] }
clap_complete = "4.3.1"
clap_mangen = "0.2.15"
crossterm = { workspace = true }
dialoguer = { version = "0.11", default-features = false, features = ["password"] }
dirs = { workspace = true }
dunce = { workspace = true }
flate2 = { workspace = true }
futures = { workspace = true }
git2 = { version = "0.19.0", default-features = false }
gix = { version = "0.66.0", default-features = false, features = [
  "blocking-http-transport-reqwest-rust-tls",
  "worktree-mutation",
] }
globset = "0.4.13"
headers = { workspace = true }
home = { workspace = true }
hyper = { workspace = true }
ignore = "0.4.20"
indicatif = "0.17.3"
indoc = "2.0.1"
portpicker = { workspace = true }
regex = "1.9.5"
reqwest = { workspace = true }
rmp-serde = { workspace = true }
semver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
strum = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tokio-tungstenite = { workspace = true }
toml = { workspace = true }
toml_edit = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true, features = ["default"] }
tracing-subscriber = { workspace = true, features = [
  "default",
  "env-filter",
  "fmt",
] }
url = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
walkdir = "2.3.3"
webbrowser = "1.0.1"
zip = "2.2.0"

[dev-dependencies]
assert_cmd = "2.0.6"
rexpect = "0.5.0"
# Publication of this crate will fail if this is changed to a workspace dependency
shuttle-common-tests = { path = "../common-tests" }
