[package]
name = "shuttle-actix-web"
version = "0.44.0"
edition = "2021"
license = "Apache-2.0"
description = "Service implementation to run an actix webserver on shuttle"
repository = "https://github.com/shuttle-hq/shuttle"
keywords = ["shuttle-service", "actix"]

[workspace]

[dependencies]
actix-web = "4.3.1"
num_cpus = "1.15.0"
shuttle-runtime = { path = "../../runtime", version = "0.44.0", default-features = false }
