[package]
name = "serenity-postgres"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
serde = "1.0"
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
shuttle-service = { version = "0.5.0", features = ["bot-serenity", "secrets", "sqlx-postgres"] }
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "postgres"] }
tracing = "0.1.36"
