[package]
name = "shuttle-qdrant"
version = "0.45.0"
edition = "2021"
license = "Apache-2.0"
description = "Shuttle plugin for connecting to a Qdrant database"
repository = "https://github.com/shuttle-hq/shuttle"
keywords = ["shuttle-service", "qdrant"]

[dependencies]
async-trait = "0.1.56"
qdrant-client = "1.7.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shuttle-service = { path = "../../service", version = "0.45.0" }
