[package]
name = "shuttle-codegen"
version = "0.3.1"
edition = "2021"
license = "Apache-2.0"
description = "Proc-macro code generator for the shuttle.rs service"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.39"
quote = "1.0.18"
syn = { version = "1.0.96", features = ["full"] }

[dev-dependencies]
pretty_assertions = "1.2.1"
