[package]
name = "shuttle-tower"
version = "0.43.0"
edition = "2021"
license = "Apache-2.0"
description = "Service implementation to run a tower webserver on shuttle"
repository = "https://github.com/shuttle-hq/shuttle"
keywords = ["shuttle-service", "tower"]

[workspace]

[dependencies]
hyper = { version = "0.14.23", features = ["server", "tcp", "http1"] }
shuttle-runtime = { path = "../../runtime", version = "0.43.0", default-features = false }
tower = { version = "0.4.13", features = ["make"] }
