[package]
name = "shuttle-next"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "shuttle-next"

[dependencies]
async-trait = "0.1.58"
clap ={ version = "4.0.18", features = ["derive"] }
tokio = { version = "1.20.1", features = [ "full" ] }
tonic = "0.8.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

cap-std = "*"
wasmtime = "*"
wasmtime-wasi = "*"
wasi-common = "*"

serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }

[dependencies.shuttle-runtime-proto]
version = "0.1.0"
path = "../proto"
