[package]
name = "shuttle-turso"
version = "0.45.0"
edition = "2021"
license = "Apache-2.0"
description = "Plugin to obtain a client connected to a Turso database"
repository = "https://github.com/shuttle-hq/shuttle"
keywords = ["shuttle-service", "turso"]

[dependencies]
async-trait = "0.1.56"
dunce = "1.0.4"
libsql = { version = "0.3.1", default-features = false, features = ["core", "remote"] }
serde = { version = "1", features = ["derive"] }
shuttle-service = { path = "../../service", version = "0.45.0" }
url = { version = "2.3.1", features = ["serde"] }

[dev-dependencies]
tempfile = "3.3.0"
tokio = { version = "1.28.2", features = ["rt-multi-thread", "macros"] }
