[package]
name = "e2e"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
crossterm = "0.26.1"
lazy_static = "1.4.0"
portpicker = "0.1.1"
rand = "0.8.5"
reqwest = { version = "0.11.10", features = ["blocking", "json"] }
which = "4.2.5"
tempfile = "3.3.0"
