[package]
name = "shuttle-poem"
version = "0.45.0"
edition = "2021"
license = "Apache-2.0"
description = "Service implementation to run a poem webserver on shuttle"
repository = "https://github.com/shuttle-hq/shuttle"
keywords = ["shuttle-service", "poem"]

[workspace]

[dependencies]
poem = "3.0.0"
shuttle-runtime = { path = "../../runtime", version = "0.45.0", default-features = false }
