[package]
name = "shuttle-poem"
version = "0.1.0"
edition = "2021"

[workspace]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poem = { version = "1.3.55" }
shuttle-runtime = { path = "../../runtime", version = "0.1.0" }
