[package]
name = "shuttle-rocket"
version = "0.13.0"
edition = "2021"
license = "Apache-2.0"
description = "Service implementation to run a rocket webserver on shuttle"
keywords = ["shuttle-service", "rocket"]

[workspace]

[dependencies]
rocket = { version = "0.5.0-rc.2" }
shuttle-runtime = { path = "../../runtime", version = "0.13.0" }

[dev-dependencies]
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
