[package]
name = "shuttle-rocket"
version = "0.46.0"
edition = "2021"
license = "Apache-2.0"
description = "Service implementation to run a rocket webserver on shuttle"
repository = "https://github.com/shuttle-hq/shuttle"
keywords = ["shuttle-service", "rocket"]

[workspace]

[dependencies]
rocket = "0.5.0"
shuttle-runtime = { path = "../../runtime", version = "0.46.0", default-features = false }
