[package]
name = "shuttle-admin"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.62"
clap = { version = "4.0.0", features = [ "derive", "env" ] }
dirs = "4.0.0"
reqwest = { version = "0.11.11", features = ["json"] }
tokio = { version = "1.20.1", features = ["macros"] }
toml = "0.5.9"
