[package]
name = "proto"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.10.4"
tonic = "0.7.2"

[dependencies.shuttle-common]
version = "0.3.1"
path = "../common"

[build-dependencies]
tonic-build = "0.7.2"
