[package]
name = "shuttle-proto"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
home = "0.5.4"
prost = "0.11.2"
prost-types = { workspace = true }
tokio = { version = "1.22.0", features = ["process"] }
tonic = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

[dependencies.shuttle-common]
workspace = true
features = ["error", "service", "wasm"]

[build-dependencies]
tonic-build = "0.8.3"
