[package]
name = "shuttle-proto"
version = "0.4.2"
edition = "2021"
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.10.4"
tonic = "0.7.2"

[dependencies.shuttle-common]
version = "0.4.2"
path = "../common"

[build-dependencies]
tonic-build = "0.7.2"
