[package]
name = "shuttle-persist"
version = "0.6.0"
edition = "2021"
license = "Apache-2.0"
description = "Plugin for persist objects"
keywords = ["shuttle-service", "persistence"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.56"
bincode = "1.2.1"
serde = { version = "1.0.0", features = ["derive"] }
shuttle-common = { path = "../../common", version = "0.7.0" }
shuttle-service = { path = "../../service", version = "0.7.0", default-features = false }
thiserror = "1.0.32"
tokio = { version = "1.19.2", features = ["rt"] }
