[package]
name = "shuttle-common"
version = "0.5.0"
edition = "2021"
license = "Apache-2.0"
description = "Common library for the shuttle platform (https://www.shuttle.rs/)"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.62"
chrono = { version = "0.4.22", features = ["serde"] }
comfy-table = "6.0.0"
crossterm = "0.23.2"
once_cell = "1.13.1"
rocket = "0.5.0-rc.2"
rustrict = "0.5.0"
serde = "1.0.137"
serde_json = "1.0.81"
strum = { version = "0.24.1", features = ["derive"] }
uuid = { version = "1.1.1", features = ["v4", "serde"] }
