[package]
name = "shuttle-tower"
version = "0.1.0"
edition = "2021"

[workspace]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14.23", features = ["server", "tcp", "http1"] }
shuttle-runtime = { path = "../../runtime", version = "0.1.0" }
tower = { version = "0.4.13", features = ["make"] }
