[package]
name = "shuttle-secrets"
version = "0.14.0"
edition = "2021"
license = "Apache-2.0"
description = "Plugin to for managing secrets on shuttle"
keywords = ["shuttle-service", "secrets"]

[dependencies]
async-trait = "0.1.56"
serde = { version = "1.0.148", features = ["derive"] }
shuttle-service = { path = "../../service", version = "0.14.0", default-features = false }
