[patch.crates-io]
shuttle-codegen = { path = "BASE/codegen" }
shuttle-common = { path = "BASE/common" }
shuttle-proto = { path = "BASE/proto" }
shuttle-runtime = { path = "BASE/runtime" }
shuttle-service = { path = "BASE/service" }

shuttle-aws-rds = { path = "BASE/resources/aws-rds" }
shuttle-openai = { path = "BASE/resources/openai" }
shuttle-opendal = { path = "BASE/resources/opendal" }
shuttle-persist = { path = "BASE/resources/persist" }
shuttle-qdrant = { path = "BASE/resources/qdrant" }
shuttle-shared-db = { path = "BASE/resources/shared-db" }
shuttle-turso = { path = "BASE/resources/turso" }

shuttle-axum = { path = "BASE/services/shuttle-axum" }
shuttle-actix-web = { path = "BASE/services/shuttle-actix-web" }
shuttle-poem = { path = "BASE/services/shuttle-poem" }
shuttle-rocket = { path = "BASE/services/shuttle-rocket" }
shuttle-salvo = { path = "BASE/services/shuttle-salvo" }
shuttle-serenity = { path = "BASE/services/shuttle-serenity" }
shuttle-thruster = { path = "BASE/services/shuttle-thruster" }
shuttle-tide = { path = "BASE/services/shuttle-tide" }
shuttle-tower = { path = "BASE/services/shuttle-tower" }
shuttle-warp = { path = "BASE/services/shuttle-warp" }
