[package]
name = "shuttle-shared-db"
version = "0.47.0"
edition = "2021"
license = "Apache-2.0"
description = "Plugin for managing shared databases on shuttle"
repository = "https://github.com/shuttle-hq/shuttle"
keywords = ["shuttle-service", "database"]

[dependencies]
async-trait = "0.1.56"
diesel-async = { version = "0.4.1", optional = true }
mongodb = { version = "2.3.0", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shuttle-service = { path = "../../service", version = "0.47.0" }
sqlx = { version = "0.8.2", optional = true }

[features]
default = []

# Mongodb
mongodb = ["dep:mongodb"]

# Postgres
postgres = ["diesel-async?/postgres", "sqlx?/postgres"]
# Postgres with diesel-async support
diesel-async = ["dep:diesel-async"]
diesel-async-bb8 = ["diesel-async", "diesel-async/bb8"]
diesel-async-deadpool = ["diesel-async", "diesel-async/deadpool"]
# Postgres with an sqlx PgPool
sqlx = ["dep:sqlx", "sqlx/runtime-tokio", "sqlx/tls-rustls"]
sqlx-native-tls = ["dep:sqlx", "sqlx/runtime-tokio", "sqlx/tls-native-tls"]
