[package]
name = "shuttle-shared-db"
version = "0.36.0"
edition = "2021"
license = "Apache-2.0"
description = "Plugin for managing shared databases on shuttle"
keywords = ["shuttle-service", "database"]

[dependencies]
async-trait = "0.1.56"
mongodb = { version = "2.3.0", optional = true }
serde = { version = "1.0.148", features = ["derive"] }
shuttle-service = { path = "../../service", version = "0.36.0" }
sqlx = { version = "0.7.1", optional = true }

[features]
default = []

# Mongodb
mongodb = ["dep:mongodb"]

# Postgres
postgres = ["sqlx?/postgres", "sqlx?/runtime-tokio", "sqlx?/tls-native-tls"]
postgres-rustls = ["sqlx?/postgres", "sqlx?/runtime-tokio", "sqlx?/tls-rustls"]
# Postgres with an sqlx PgPool
sqlx = ["dep:sqlx"]
