[package]
name = "shuttle-builder"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait = { workspace = true }
flate2 = { workspace = true }
nbuild-core = "0.1.1"
tar = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "io-util", "process", "rt-multi-thread"] }
toml = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
ulid = { workspace = true }

[dependencies.shuttle-common]
workspace = true
features = ["backend", "tonic"]

[dependencies.shuttle-proto]
workspace = true

[dev-dependencies]
hyper = { workspace = true }
portpicker = { workspace = true }
pretty_assertions = { workspace = true }
tower = { workspace = true }
