[package]
name = "shuttle-deployer"
version = "0.1.0"
edition = "2021"
description = "Service with instances created per project for handling the compilation, loading, and execution of Shuttle services"

[dependencies]
anyhow = "1.0.58"
async-trait = "0.1.56"
axum = { version = "0.5.7", features = ["headers", "ws"] }
bytes = "1.1.0"
cargo = "0.64.0"
cargo_metadata = "0.15.0"
chrono = "0.4.19"
clap = { version = "3.2.8", features = ["derive"] }
crossbeam-channel = "0.5.6"
flate2 = "1.0.24"
fqdn = "0.2.2"
futures = "0.3.21"
hyper = { version = "0.14.20", features = ["client", "http1", "http2", "tcp" ] }
# not great, but waiting for WebSocket changes to be merged
hyper-reverse-proxy = { git = "https://github.com/chesedo/hyper-reverse-proxy", branch = "master" }
log = "0.4.17"
once_cell = "1.14.0"
opentelemetry = { version = "0.17.0", features = ["rt-tokio"] }
opentelemetry-datadog = { version = "0.5.0", features = ["reqwest-client"] }
portpicker = "0.1.1"
rand = "0.8.5"
serde = "1.0.137"
serde_json = "1.0.81"
sqlx = { version = "0.6.0", features = ["runtime-tokio-native-tls", "sqlite", "chrono", "json", "uuid"] }
strum = { version = "0.24.1", features = ["derive"] }
tar = "0.4.38"
thiserror = "1.0.24"
tokio = { version = "1.19.2", features = ["fs"] }
toml = "0.5.9"
tonic = "0.8.0"
tower = { version = "0.4.12", features = ["make"] }
tower-http = { version = "0.3.4", features = ["trace"] }
tracing = "0.1.35"
tracing-opentelemetry = "0.17.4"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
uuid = { version = "1.1.2", features = ["v4"] }

[dependencies.shuttle-common]
version = "0.5.2"
path = "../common"

[dependencies.shuttle-proto]
version = "0.5.2"
path = "../proto"

[dependencies.shuttle-service]
version = "0.5.2"
path = "../service"
features = ["loader"]

[dev-dependencies]
ctor = "0.1.22"
hex = "0.4.3"
tempdir = "0.3.7"
