[package]
name = "shuttle-deployer"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description = "Service to execute the deployment of projects on shuttle"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true, features = ["headers", "json", "query", "ws"] }
base16ct = { version = "0.1.1", features = ["alloc"] }
bytes = { workspace = true }
clap = { workspace = true }
dirs = { workspace = true }
flate2 = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
hyper = { workspace = true, features = ["client", "http1", "http2", "tcp"] }
hyper-reverse-proxy = { git = "https://github.com/chesedo/hyper-reverse-proxy", branch = "master" }
oci-spec = "0.5.7"
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.10.2"
regex = "1.5.6"
tar = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "fs"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
ureq = { version = "2.5.0", features = ["json"] }
url = { workspace = true }
utoipa = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

[dependencies.shuttle-common]
workspace = true
features = ["backend", "models", "openapi"]
