[package]
name = "shuttle-serenity"
version = "0.34.1"
edition = "2021"
license = "Apache-2.0"
description = "Service implementation to run a serenity server on shuttle"
keywords = ["shuttle-service", "serenity"]

[workspace]

[dependencies]
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "model"], optional = true }
serenity-0-12 = { package = "serenity", version = "0.12", default-features = false, features = ["client", "gateway", "model", "rustls_backend"], optional = true }
shuttle-runtime = { path = "../../runtime", version = "0.34.1", default-features = false }

[dev-dependencies]
anyhow = "1.0.69"
shuttle-secrets = { path = "../../resources/secrets" }
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.37"

[features]
default = ["rustls_backend"]

rustls_backend = ["serenity/rustls_backend"]
native_tls_backend = ["serenity/native_tls_backend"]
serenity-0-12-rustls_backend = ["serenity-0-12/rustls_backend"]
serenity-0-12-native_tls_backend = ["serenity-0-12/native_tls_backend"]
