[package]
name = "shuttle-serenity"
version = "0.12.0-rc1"
edition = "2021"

[workspace]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
shuttle-runtime = { path = "../../runtime", version = "0.12.0-rc1" }

[dev-dependencies]
anyhow = "1.0.69"
shuttle-secrets = { path = "../../resources/secrets" }
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.37"
