[package]
name = "shuttle-serenity"
version = "0.42.0"
edition = "2021"
license = "Apache-2.0"
description = "Service implementation to run a serenity server on shuttle"
keywords = ["shuttle-service", "serenity"]

[workspace]

[dependencies]
serenity = { version = "0.12", default-features = false, features = ["client", "gateway", "model"], optional = true }
serenity-0-11 = { package = "serenity", version = "0.11.7", default-features = false, features = ["client", "gateway", "model"], optional = true }
shuttle-runtime = { path = "../../runtime", version = "0.42.0", default-features = false }

[features]
default = ["rustls_backend"]

rustls_backend = ["serenity/rustls_backend"]
native_tls_backend = ["serenity/native_tls_backend"]
serenity-0-11-rustls_backend = ["serenity-0-11/rustls_backend"]
serenity-0-11-native_tls_backend = ["serenity-0-11/native_tls_backend"]
