[package]
name = "shuttle-warp"
version = "0.46.0"
edition = "2021"
license = "Apache-2.0"
description = "Service implementation to run a warp webserver on shuttle"
repository = "https://github.com/shuttle-hq/shuttle"
keywords = ["shuttle-service", "warp"]

[workspace]

[dependencies]
warp = "0.3.3"
shuttle-runtime = { path = "../../runtime", version = "0.46.0", default-features = false }
