[package]
name = "shuttle-warp"
version = "0.15.0"
edition = "2021"
license = "Apache-2.0"
description = "Service implementation to run a warp webserver on shuttle"
keywords = ["shuttle-service", "warp"]

[workspace]

[dependencies]
warp = { version = "0.3.3" }
shuttle-runtime = { path = "../../runtime", version = "0.15.0" }

[dev-dependencies]
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
