[package]
name = "provisioner"
version = "0.1.0"
edition = "2021"
description = "Service responsible for provisioning and managing resources for services"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.12"
aws-sdk-rds = "0.12"
aws-smithy-types = "0.42"
clap = { version = "3.1.18", features = ["derive", "env"] }
fqdn = "0.1.9"
prost = "0.10.4"
rand = "0.8.5"
sqlx = { version = "0.5.13", features = ["postgres", "runtime-tokio-native-tls"] }
thiserror = "1.0.31"
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }
tonic = "0.7.2"
tracing = "0.1.35"
tracing-subscriber = "0.3.11"

[dependencies.proto]
version = "0.1.0"
path = "../proto"

[dev-dependencies]
ctor = "0.1.22"
lazy_static = "1.4.0"
portpicker = "0.1.1"

[build-dependencies]
tonic-build = "0.7.2"
