[package]
name = "shuttle-provisioner"
version = "0.6.0"
edition = "2021"
description = "Service responsible for provisioning and managing resources for services"
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.47.0"
aws-sdk-rds = "0.17.0"
aws-smithy-types = "0.47.0"
clap = { version = "3.2.17", features = ["derive", "env"] }
fqdn = "0.2.2"
mongodb = "2.3.0"
prost = "0.11.0"
rand = "0.8.5"
sqlx = { version = "0.6.1", features = ["postgres", "runtime-tokio-native-tls"] }
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }
tonic = "0.8.0"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"

[dependencies.shuttle-proto]
version = "0.6.0"
path = "../proto"

[dev-dependencies]
ctor = "0.1.23"
once_cell = "1.13.1"
portpicker = "0.1.1"
serde_json = "1.0.83"

[build-dependencies]
tonic-build = "0.8.0"
