[package]
name = "shuttle-rocket"
version = "0.1.0"
edition = "2021"

[workspace]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.2" }
shuttle-runtime = { path = "../../runtime", version = "0.1.0" }
