[package]
name = "shuttle-thruster"
version = "0.12.0-rc1"
edition = "2021"

[workspace]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thruster = { version = "1.3.0" }
shuttle-runtime = { path = "../../runtime", version = "0.12.0-rc1" }

[dev-dependencies]
thruster = { version = "1.3.0", features = ["hyper_server"] }
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
