[package]
name = "shuttle-thruster"
version = "0.12.0"
edition = "2021"
license = "Apache-2.0"
description = "Service implementation to run a thruster webserver on shuttle"
keywords = ["shuttle-service", "thruster"]

[workspace]

[dependencies]
thruster = { version = "1.3.0" }
shuttle-runtime = { path = "../../runtime", version = "0.12.0" }

[dev-dependencies]
thruster = { version = "1.3.0", features = ["hyper_server"] }
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
