[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["uuid", "serde_json", "json"] }
cargo = "0.59.0"
cargo-util = "0.1"
anyhow = "1.0.54"
libloading = "0.7.3"
futures = "0.3"
lib = { path = "../lib/" }
unveil-service = { path = "../service/" }
uuid = { version = "0.8.2", features = ["v4"] }
async-mutex = "1.4.0"
serde = "1.0.136"
structopt = "0.3.26"
sqlx = { version = "0.5", features = ["runtime-tokio-native-tls", "postgres"] }
tokio = { version = "1.15.0", features = ["full"] }
# not great, but the changes for hyper 0.14 and tokio 1 have not been merged on the main repo
hyper-reverse-proxy = { git = "https://github.com/jtroo/hyper-reverse-proxy" }
hyper = { version = "0.14", features = ["client", "http1", "http2", "tcp" ] } # for reverse proxying
log = "0.4.14"
env_logger = "0.9.0"
async-trait = "0.1.52"
lazy_static = "1.4.0"
toml = "0.5.8"
base64 = "0.13.0"
rand = "0.8.5"
