[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["uuid", "serde_json", "json"] }
cargo = "0.59.0"
anyhow = "1.0.54"
libloading = "0.7.3"
lib = { path = "../lib/" }
service = { path = "../service/" }
uuid = { version = "0.8.2", features = ["v4"] }
async-mutex = "1.4.0"
serde = "1.0.136"
