name: cargo-fmt

on:
  pull_request:
    branches: [main]
    paths: ["**/*.rs"]

  workflow_dispatch:

jobs:
  fmt_test:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/checkout@v2
      - uses: shuttle-hq/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt
      - run: cargo fmt --all -- --check
  clippy_test:
    strategy:
      fail-fast: true
      matrix:
        features: ["web-axum", "web-rocket", "web-tide", "web-tower"]
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/checkout@v2
      - uses: shuttle-hq/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy
      - name: Run test with ${{ matrix.features}}
        run: cargo clippy --tests --all-targets --features=${{ matrix.features }} -- --D warnings