name: cargo-test

on:
  push:
    branches: [main]
    paths: ["**/*.rs"]
  pull_request:
    branches: [main]
    #paths: ["**/*.rs"]

  workflow_dispatch:

jobs:
  cargo_test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Make config file
        run: mkdir -p ~/.config/unveil/ && echo "api_key = \"ci-test\"" > ~/.config/unveil/config.toml
      - name: Use local unveil-service
        run: mkdir -p ~/.cargo && echo -e "[patch.crates-io]\nunveil-service = { path = \"${GITHUB_WORKSPACE}/service\" }" > ~/.cargo/config.toml
      - run: cargo test
